export const FETCH_LESSON_LIST = 'FETCH_LESSON_LIST';
export const FETCH_LESSON_LIST_SUCCESS = 'FETCH_LESSON_LIST_SUCCESS';
export const FETCH_LESSON_LIST_FAIL = 'FETCH_LESSON_LIST_FAIL';

export const CHECKED_LESSON = 'CHECKED_LESSON';
export const CHECK_ALL_LESSONS = 'CHECK_ALL_LESSON';
export const UNCHECK_ALL_LESSONS = 'UNCHECK_ALL_LESSONS'
