const uuidv4 = require('uuid/v4');
export default [
  {
    id: uuidv4(),
    status: 'complete',
    title: 'Practice Test 1',
    testDate: '05/12/2019',
    dueDate: '05/05/2019',
    completionDate: '05/12/2019',
    completionTime: '4:21 PM',
    weekNumber: '3',
    version: '1234',
    initialScore: '1050',
    targetScore: '1500',
    currentScore: '1245',
    totalGain: '132',
    subjects: [
      {
        subject: 'Reading & Writing',
        targetScore: '750',
        currentScore: '454',
        totalGain: '73',
      },
      {
        subject: 'Math',
        targetScore: '490',
        currentScore: '345',
        totalGain: '101',
      },
    ],
    compositeScore: {
      reading: '83',
      writing: '31',
      math: '105',
      composite: '218',
    },
    subjectScores: {
      reading: '58',
      writing: '44',
      math: '91',
      composite: '195',
    },
    totalScore: '1080',
    totalPossible: '1600',
    sectionScores: {
      readingAndWriting: '710',
      math: '650',
      totalPossible: '800',
    },
    essayScores: {
      reading: '7',
      analysis: '6',
      writing: '7',
      totalPossible: '8',
    },
    crossTestScores: '24',
    subScores: {
      commandOfEvidence: '5',
      wordsInContext: '12',
      expressionOfIdeas: '12',
      standardEnglishConventions: '14',
      heartOfAlgebra: '10',
      problemSolvingAndDataAnalysis: '10',
      passportToAdvancedMath: '13',
      totalPossible: '15',
    },
    testScoreDetails: {
      reading: {
        totalCorrect: '39',
        totalPossible: '59',
        passageType: {
          science: '11',
          informationalGraphicPassage: '12',
          historySocialScience: '13',
          USWorldLiterature: '14',
          pairedPassages: '12',
        },
        questionType: {
          citingTextualEvidence: {
            citeTextAsEvidence: '12',
            authorsIntentionAndMethod: '12',
            supportOrRefute: '12',
          },
          readingClosely: {
            detailQuestion: '12',
            supportRefuteAClaim: '13',
          },
        },
      },
      mathCalculator: {
        sampleAnswers: [
          {
            id: 11,
            topic: 'topic1',
            problem: 1,
            answer: "A",
            studentChoice: "B",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 12,
            topic: 'topic2',
            problem: 1,
            answer: "B",
            studentChoice: "B",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 13,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 14,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "A",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 21,
            topic: 'topic1',
            problem: 1,
            answer: "A",
            studentChoice: "B",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 22,
            topic: 'topic2',
            problem: 1,
            answer: "B",
            studentChoice: "B",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 23,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 24,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "A",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 25,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
        ],
      },
      mathNoCalc: {
        sampleAnswers: [
          {
            id: 11,
            topic: 'topic1',
            problem: 1,
            answer: "B",
            studentChoice: "A",
            correct: false,
            status: 'E',
            flagged: false,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 12,
            topic: 'topic2',
            problem: 1,
            answer: "A",
            studentChoice: "",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 13,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 14,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "D",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 21,
            topic: 'topic1',
            problem: 1,
            answer: "A",
            studentChoice: "B",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 22,
            topic: 'topic2',
            problem: 1,
            answer: "B",
            studentChoice: "B",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 23,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 24,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "A",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 25,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
        ],
      },
      writing: {
        sampleAnswers: [
          {
            id: 11,
            numeric: false,
            topic: 'writing',
            problem: 1,
            answer: "B",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 12,
            numeric: false,
            topic: 'writing',
            problem: 2,
            answer: "D",
            studentChoice: "D",
            correct: true,
            status: 'M',
            flagged: false,
            reviewed: false,
            studentNotes: "Lorem ipsum dolor sit amet sed diam nonummy nibh euismod tincidunt ut laoreet dolore?  tincidunt ut laoreet dolore?",
            tutorNotes: "work and study hard",
          },
          {
            id: 13,
            numeric: true,
            topic: 'writing',
            problem: 3,
            answer: 1492,
            studentChoice: 1492,
            correct: true,
            status: 'M',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 14,
            numeric: true,
            topic: 'writing',
            problem: 4,
            answer: 1.25,
            studentChoice: 5.71,
            correct: false,
            status: 'E  ',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          }, {
            id: 21,
            numeric: false,

            topic: 'topic1',
            problem: 1,
            answer: "A",
            studentChoice: "B",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 22,
            numeric: false,
            topic: 'topic2',
            problem: 1,
            answer: "B",
            studentChoice: "B",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 23,
            numeric: false,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 24,
            numeric: false,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "A",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 25,
            numeric: false,
            opic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
        ],
      },
    },
    },
  {
    id: uuidv4(),
    status: 'complete',
    title: 'Practice Test 2',
    testDate: '07/01/2019',
    dueDate: '05/05/2019',
    completionDate: '05/07/2019',
    completionTime: '4:21 PM',
    weekNumber: '3',
    version: '2345',
    initialScore: '1100',
    targetScore: '1320',
    currentScore: '1221',
    totalGain: '98',
    subjects: [
      {
        subject: 'Reading & Writing',
        targetScore: '730',
        currentScore: '421',
        totalGain: '67',
      },
      {
        subject: 'Math',
        targetScore: '488',
        currentScore: '367',
        totalGain: '121',
      },
    ],
    compositeScore: {
      reading: '83',
      writing: '31',
      math: '105',
      composite: '218',
    },
    subjectScores: {
      reading: '58',
      writing: '44',
      math: '91',
      composite: '195',
    },
    totalScore: '1080',
    totalPossible: '1600',
    sectionScores: {
      readingAndWriting: '710',
      math: '650',
      totalPossible: '800',
    },
    essayScores: {
      reading: '7',
      analysis: '6',
      writing: '7',
      totalPossible: '8',
    },
    crossTestScores: '24',
    subScores: {
      commandOfEvidence: '5',
      wordsInContext: '12',
      expressionOfIdeas: '12',
      standardEnglishConventions: '14',
      heartOfAlgebra: '10',
      problemSolvingAndDataAnalysis: '10',
      passportToAdvancedMath: '13',
      totalPossible: '15',
    },
    testScoreDetails: {
      reading: {
        totalCorrect: '39',
        totalPossible: '59',
        passageType: {
          science: '11',
          informationalGraphicPassage: '12',
          historySocialScience: '13',
          USWorldLiterature: '14',
          pairedPassages: '12',
        },
        questionType: {
          citingTextualEvidence: {
            citeTextAsEvidence: '12',
            authorsIntentionAndMethod: '12',
            supportOrRefute: '12',
          },
          readingClosely: {
            detailQuestion: '12',
            supportRefuteAClaim: '13',
          },
        },
      },
      mathCalculator: {
        sampleAnswers: [
          {
            id: 11,
            topic: 'topic1',
            problem: 1,
            answer: "A",
            studentChoice: "B",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 12,
            topic: 'topic2',
            problem: 1,
            answer: "B",
            studentChoice: "B",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 13,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 14,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "A",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 21,
            topic: 'topic1',
            problem: 1,
            answer: "A",
            studentChoice: "B",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 22,
            topic: 'topic2',
            problem: 1,
            answer: "B",
            studentChoice: "B",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 23,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 24,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "A",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 25,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
        ],
      },
      mathNoCalc: {
        sampleAnswers: [
          {
            id: 11,
            topic: 'topic1',
            problem: 1,
            answer: "B",
            studentChoice: "A",
            correct: false,
            status: 'E',
            flagged: false,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 12,
            topic: 'topic2',
            problem: 1,
            answer: "A",
            studentChoice: "",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 13,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 14,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "D",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 21,
            topic: 'topic1',
            problem: 1,
            answer: "A",
            studentChoice: "B",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 22,
            topic: 'topic2',
            problem: 1,
            answer: "B",
            studentChoice: "B",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 23,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 24,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "A",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 25,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
        ],
      },
      writing: {
        sampleAnswers: [
          {
            id: 11,
            numeric: false,
            topic: 'writing',
            problem: 1,
            answer: "B",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 12,
            numeric: false,
            topic: 'writing',
            problem: 2,
            answer: "D",
            studentChoice: "D",
            correct: true,
            status: 'M',
            flagged: false,
            reviewed: false,
            studentNotes: "Lorem ipsum dolor sit amet sed diam nonummy nibh euismod tincidunt ut laoreet dolore?  tincidunt ut laoreet dolore?",
            tutorNotes: "work and study hard",
          },
          {
            id: 13,
            numeric: true,
            topic: 'writing',
            problem: 3,
            answer: 1492,
            studentChoice: 1492,
            correct: true,
            status: 'M',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 14,
            numeric: true,
            topic: 'writing',
            problem: 4,
            answer: 1.25,
            studentChoice: 5.71,
            correct: false,
            status: 'E  ',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          }, {
            id: 21,
            numeric: false,

            topic: 'topic1',
            problem: 1,
            answer: "A",
            studentChoice: "B",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: true,
            tutorNotes: "work and study hard",
          },
          {
            id: 22,
            numeric: false,
            topic: 'topic2',
            problem: 1,
            answer: "B",
            studentChoice: "B",
            correct: true,
            status: 'E',
            flagged: false,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 23,
            numeric: false,
            topic: 'topic3',
            problem: 1,
            answer: "C",
            studentChoice: "",
            correct: false,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 24,
            numeric: false,
            topic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "A",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
          {
            id: 25,
            numeric: false,
            opic: 'topic4',
            problem: 1,
            answer: "D",
            studentChoice: "",
            correct: true,
            status: 'E',
            flagged: true,
            reviewed: false,
            tutorNotes: "work and study hard",
          },
        ],
      },
    },
  },
  {
    id: uuidv4(),
    status: 'complete',
    title: 'Practice Test 3',
    testDate: '11/25/2019',
    dueDate: '05/05/2019',
    completionDate: '',
    completionTime: '',
    weekNumber: '3',
    version: '3456',
    initialScore: '1026',
    targetScore: '1455',
    currentScore: '1102',
    totalGain: '154',
    subjects: [
      {
        subject: 'Reading & Writing',
        targetScore: '753',
        currentScore: '642',
        totalGain: '91',
      },
      {
        subject: 'Math',
        targetScore: '467',
        currentScore: '401',
        totalGain: '163',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'future',
    title: 'Practice Test 4',
    testDate: '12/12/2019',
    dueDate: '05/05/2019',
    completionDate: '',
    completionTime: '',
    weekNumber: '3',
    // version: '3456',
    // initialScore: '1026',
    // targetScore: '1455',
    // currentScore: '1102',
    // totalGain: '154',
    subjects: [
      {
        // subject: 'Reading & Writing',
        // targetScore: '753',
        // currentScore: '642',
        // totalGain: '91',
      },
      {
        // subject: 'Math',
        // targetScore: '467',
        // currentScore: '401',
        // totalGain: '163',
      },
    ],
  },
  {
    id: uuidv4(),
    status: 'future',
    title: 'Practice Test 5',
    testDate: '12/23/2019',
    dueDate: '05/05/2019',
    completionDate: '',
    completionTime: '',
    weekNumber: '3',
    // version: '3456',
    // initialScore: '1026',
    // targetScore: '1455',
    // currentScore: '1102',
    // totalGain: '154',
    subjects: [
      {
        // subject: 'Reading & Writing',
        // targetScore: '753',
        // currentScore: '642',
        // totalGain: '91',
      },
      {
        // subject: 'Math',
        // targetScore: '467',
        // currentScore: '401',
        // totalGain: '163',
      },
    ],
  },
];
