export default [
  {
    id: 1,
    status: 'complete',
    title: 'Practice Test 1',
    testDate: '05/12/2019',
    dueDate: '05/05/2019',
    completionDate: '05/12/2019',
    completionTime: '4:21 PM',
    weekNumber: '3',
    version: '1234',
    initialScore: '1050',
    targetScore: '1500',
    currentScore: '1245',
    totalGain: '132',
    subjects: [
      {
        subject: 'Reading & Writing',
        targetScore: '750',
        currentScore: '454',
        totalGain: '73',
      },
      {
        subject: 'Math',
        targetScore: '490',
        currentScore: '345',
        totalGain: '101',
      },
    ],
  },
  {
    id: 2,
    status: 'complete',
    title: 'Practice Test 2',
    testDate: '07/01/2019',
    dueDate: '05/05/2019',
    completionDate: '05/07/2019',
    completionTime: '4:21 PM',
    weekNumber: '3',
    version: '2345',
    initialScore: '1100',
    targetScore: '1320',
    currentScore: '1221',
    totalGain: '98',
    subjects: [
      {
        subject: 'Reading & Writing',
        targetScore: '730',
        currentScore: '421',
        totalGain: '67',
      },
      {
        subject: 'Math',
        targetScore: '488',
        currentScore: '367',
        totalGain: '121',
      },
    ],
  },
  {
    id: 3,
    status: 'complete',
    title: 'Practice Test 3',
    testDate: '11/25/2019',
    dueDate: '05/05/2019',
    completionDate: '',
    completionTime: '',
    weekNumber: '3',
    version: '3456',
    initialScore: '1026',
    targetScore: '1455',
    currentScore: '1102',
    totalGain: '154',
    subjects: [
      {
        subject: 'Reading & Writing',
        targetScore: '753',
        currentScore: '642',
        totalGain: '91',
      },
      {
        subject: 'Math',
        targetScore: '467',
        currentScore: '401',
        totalGain: '163',
      },
    ],
  },
  {
    id: 4,
    status: 'future',
    title: 'Practice Test 4',
    testDate: '12/12/2019',
    dueDate: '05/05/2019',
    completionDate: '',
    completionTime: '',
    weekNumber: '3',
    // version: '3456',
    // initialScore: '1026',
    // targetScore: '1455',
    // currentScore: '1102',
    // totalGain: '154',
    subjects: [
      {
        // subject: 'Reading & Writing',
        // targetScore: '753',
        // currentScore: '642',
        // totalGain: '91',
      },
      {
        // subject: 'Math',
        // targetScore: '467',
        // currentScore: '401',
        // totalGain: '163',
      },
    ],
  },
  {
    id: 5,
    status: 'future',
    title: 'Practice Test 5',
    testDate: '12/23/2019',
    dueDate: '05/05/2019',
    completionDate: '',
    completionTime: '',
    weekNumber: '3',
    // version: '3456',
    // initialScore: '1026',
    // targetScore: '1455',
    // currentScore: '1102',
    // totalGain: '154',
    subjects: [
      {
        // subject: 'Reading & Writing',
        // targetScore: '753',
        // currentScore: '642',
        // totalGain: '91',
      },
      {
        // subject: 'Math',
        // targetScore: '467',
        // currentScore: '401',
        // totalGain: '163',
      },
    ],
  },
];
