branch-defaults:
  develop:
    environment: dev-env
    group_suffix: null
global:
  application_name: clear-choice-admin
  branch: null
  default_ec2_keyname: clear-choice-react-super-admin-dev
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
