export default [
  {
    worksheetName: 'Some SAT Problems about Triangles',
    score: '',
    problems: 15,
    timeEstimate: '14',
    assignDate: '1/27/19',
    dueDate: '2/10/19',
    completed: '',
    flags: [],
    status: 'Assigned',
    disabled: true,
    topic: 'specialRightTriangles',
  },
  {
    worksheetName: 'Worksheet 2',
    score: '',
    problems: 18,
    timeEstimate: '30',
    assignDate: '1/19/19',
    dueDate: '2/02/19',
    completed: 0,
    flags: ['one', 'two', 'three'],
    status: 'Assigned',
    disabled: false,
    topic: 'topic2',
  },
  {
    worksheetName: 'Worksheet 3',
    score: '81',
    problems: 16,
    timeEstimate: '24',
    assignDate: '1/11/19',
    dueDate: '2/12/19',
    completed: 10,
    flags: [],
    status: 'Accomplished',
    disabled: false,
    topic: 'topic2',
  },
  {
    worksheetName: 'Worksheet 4',
    score: '32',
    problems: 14,
    timeEstimate: '31',
    assignDate: '1/24/19',
    dueDate: '2/27/19',
    completed: 4,
    flags: [],
    status: 'Beginning',
    disabled: false,
    topic: 'topic3',
  },
  {
    worksheetName: 'Worksheet 5',
    score: '93',
    problems: 21,
    timeEstimate: '23',
    assignDate: '1/12/19',
    dueDate: '2/03/19',
    completed: 6,
    flags: [],
    status: 'Exemplary',
    disabled: false,
    topic: 'topic3',
  },
  {
    worksheetName: 'Worksheet 6',
    score: '64',
    problems: 30,
    timeEstimate: '65',
    assignDate: '1/09/19',
    dueDate: '2/12/19',
    completed: 5,
    flags: [],
    status: 'Developing',
    disabled: false,
    topic: 'topic4',
  },
];
