export default [
  {
    worksheetName: 'Some SAT Problems about Triangles',
    subject: 'Math',
    score: '',
    problems: 15,
    problemType: 'Skill Builder',
    difficulty: 'Beginner',
    timeEstimate: '14',
    assignDate: '1/27/19',
    availableDate: '1/27/19',
    dueDate: '2/10/19',
    completed: '',
    flags: [],
    status: 'Assigned',
    disabled: true,
    late: false,
    topic: 'specialRightTriangles',
    worksheetSource: 'Admin Created',
    classifications: ['Right Triangles', 'More Math', "Lots Of Math"],
  },
  {
    worksheetName: 'Worksheet 2',
    subject: 'Reading',
    score: '',
    problems: 18,
    problemType: 'Skill Builder',
    difficulty: 'Beginner',
    timeEstimate: '30',
    assignDate: '1/19/19',
    availableDate: '1/19/19',
    dueDate: '2/02/19',
    completed: 0,
    flags: ['one', 'two', 'three'],
    status: 'Assigned',
    disabled: false,
    late: true,
    topic: 'topic2',
    worksheetSource: 'User Created',
    classifications: ['Math', 'More Math', "Lots Of Math"],
  },
  {
    worksheetName: 'Worksheet 3',
    subject: 'Science',
    score: '81',
    problems: 16,
    problemType: 'SAT Style',
    difficulty: 'Advanced',
    timeEstimate: '24',
    assignDate: '1/11/19',
    availableDate: '1/11/19',
    dueDate: '2/12/19',
    completed: 10,
    flags: [],
    status: 'Accomplished',
    disabled: false,
    late: false,
    topic: 'topic2',
    worksheetSource: 'Admin Created',
    classifications: ['Right Triangles', 'Math', "Lots Of Math"],
  },
  {
    worksheetName: 'Worksheet 4',
    subject: 'Science',
    score: '32',
    problems: 14,
    problemType: 'SAT Style',
    difficulty: 'Mixed',
    timeEstimate: '31',
    assignDate: '1/24/19',
    availableDate: '1/24/19',
    dueDate: '2/27/19',
    completed: 4,
    flags: [],
    status: 'Beginning',
    disabled: false,
    late: true,
    topic: 'topic3',
    worksheetSource: 'User Created',
    classifications: ['Trigonometry', 'More Math', "Lots Of Math"],
  },
  {
    worksheetName: 'Worksheet 5',
    subject: 'Reading',
    score: '93',
    problems: 21,
    problemType: 'Mixed',
    difficulty: 'Mixed',
    timeEstimate: '23',
    assignDate: '1/12/19',
    availableDate: '1/12/19',
    dueDate: '2/03/19',
    completed: 6,
    flags: [],
    status: 'Exemplary',
    disabled: false,
    late: false,
    topic: 'topic3',
    worksheetSource: 'Admin Created',
    classifications: ['Trigonometry', 'Math', "Lots Of Math"],
  },
  {
    worksheetName: 'Worksheet 6',
    subject: 'Math',
    score: '64',
    problems: 30,
    problemType: 'Mixed',
    difficulty: 'Advanced',
    timeEstimate: '65',
    assignDate: '1/09/19',
    availableDate: '1/09/19',
    dueDate: '2/12/19',
    completed: 5,
    flags: [],
    status: 'Developing',
    disabled: false,
    late: false,
    topic: 'topic4',
    worksheetSource: 'User Created',
    classifications: ['Right Triangles', 'Trigonometry', 'More Math'],
  },
];
