import sampleQuestions from '../../LessonWorksheetTestSection/utils/sampleQuestions';

export default [
  {
    id: 1,
    worksheetName: 'Some SAT Problems about Triangles',
    subject: 'Math',
    score: '',
    problems: 15,
    problemType: 'Skill Builder',
    difficulty: 'Beginner',
    timeEstimate: '14',
    assignDate: '1/27/19',
    assignTime: '3:01 PM',
    availableDate: '1/27/19',
    dueDate: '2/10/19',
    dueTime: '9:32 AM',
    completedDate: '3/12/19',
    completedTime: '2:53 PM',
    completed: '',
    unit: 'Reading Unit #4',
    passage: '214',
    type: 'challenge + practice',
    flags: [],
    status: 'Assigned',
    disabled: true,
    late: false,
    topic: 'specialRightTriangles',
    worksheetSource: 'Admin Created',
    classifications: ['Right Triangles', 'More Math', "Lots Of Math"],
    questions: sampleQuestions,
  },
  {
    id: 2,
    worksheetName: 'Worksheet 2',
    subject: 'Reading',
    score: '',
    problems: 18,
    problemType: 'Skill Builder',
    difficulty: 'Beginner',
    timeEstimate: '30',
    assignDate: '1/19/19',
    assignTime: '3:01 PM',
    availableDate: '1/19/19',
    dueDate: '2/02/19',
    dueTime: '9:32 AM',
    completedDate: '',
    completedTime: '',
    completed: 0,
    unit: 'Reading Unit #4',
    passage: '51',
    type: 'challenge + practice',
    flags: ['one', 'two', 'three'],
    status: 'Assigned',
    disabled: false,
    late: true,
    topic: 'topic2',
    worksheetSource: 'User Created',
    classifications: ['Math', 'More Math', "Lots Of Math"],
    questions: sampleQuestions,
  },
  {
    id: 3,
    worksheetName: 'Worksheet 3',
    subject: 'Science',
    score: '81',
    problems: 16,
    problemType: 'SAT Style',
    difficulty: 'Advanced',
    timeEstimate: '24',
    assignDate: '1/11/19',
    assignTime: '3:01 PM',
    availableDate: '1/11/19',
    dueDate: '2/12/19',
    dueTime: '9:32 AM',
    completedDate: '3/12/19',
    completedTime: '2:53 PM',
    completed: 10,
    unit: 'Reading Unit #4',
    passage: '121',
    type: 'challenge + practice',
    flags: [],
    status: 'Accomplished',
    disabled: false,
    late: false,
    topic: 'topic2',
    worksheetSource: 'Admin Created',
    classifications: ['Right Triangles', 'Math', "Lots Of Math"],
    questions: sampleQuestions,
  },
  {
    id: 4,
    worksheetName: 'Worksheet 4',
    subject: 'Science',
    score: '32',
    problems: 14,
    problemType: 'SAT Style',
    difficulty: 'Mixed',
    timeEstimate: '31',
    assignDate: '1/24/19',
    assignTime: '3:01 PM',
    availableDate: '1/24/19',
    dueDate: '2/27/19',
    dueTime: '9:32 AM',
    completedDate: '',
    completedTime: '',
    completed: 4,
    unit: 'Reading Unit #4',
    passage: '128',
    type: 'challenge + practice',
    flags: [],
    status: 'Beginning',
    disabled: false,
    late: true,
    topic: 'topic3',
    worksheetSource: 'User Created',
    classifications: ['Trigonometry', 'More Math', "Lots Of Math"],
    questions: sampleQuestions,
  },
  {
    id: 5,
    worksheetName: 'Worksheet 5',
    subject: 'Reading',
    score: '93',
    problems: 21,
    problemType: 'Mixed',
    difficulty: 'Mixed',
    timeEstimate: '23',
    assignDate: '1/12/19',
    assignTime: '3:01 PM',
    availableDate: '1/12/19',
    dueDate: '2/03/19',
    dueTime: '9:32 AM',
    completedDate: '3/12/19',
    completedTime: '2:53 PM',
    completed: 6,
    unit: 'Reading Unit #4',
    passage: '73',
    type: 'challenge + practice',
    flags: [],
    status: 'Exemplary',
    disabled: false,
    late: false,
    topic: 'topic3',
    worksheetSource: 'Admin Created',
    classifications: ['Trigonometry', 'Math', "Lots Of Math"],
    questions: sampleQuestions,
  },
  {
    id: 6,
    worksheetName: 'Worksheet 6',
    subject: 'Math',
    score: '64',
    problems: 30,
    problemType: 'Mixed',
    difficulty: 'Advanced',
    timeEstimate: '65',
    assignDate: '1/09/19',
    assignTime: '3:01 PM',
    availableDate: '1/09/19',
    dueDate: '2/12/19',
    dueTime: '9:32 AM',
    completedDate: '',
    completedTime: '',
    completed: 5,
    unit: 'Reading Unit #4',
    passage: '153',
    type: 'challenge + practice',
    flags: [],
    status: 'Developing',
    disabled: false,
    late: false,
    topic: 'topic4',
    worksheetSource: 'User Created',
    classifications: ['Right Triangles', 'Trigonometry', 'More Math'],
    questions: sampleQuestions,
  },
];
