export default [
  {
    id: 1,
    title: 'Some SAT Problems about Triangles',
    subject: 'Math',
    problems: 15,
    type: 'Skill Builders',
    unit: 'Math Unit #2',
    difficulty: 'Easy',
    timeEstimate: '14',
    source: 'Built-In',
    classifications: ['Right Triangles', 'More Math', "Lots Of Math"],
  },
  {
    id: 2,
    title: 'Worksheet 2',
    subject: 'Reading',
    problems: 18,
    type: 'Skill Builders',
    unit: 'Reading Unit #3',
    difficulty: 'Easy',
    timeEstimate: '30',
    source: 'User Created',
    classifications: [],
  },
  {
    id: 3,
    title: 'Worksheet 3',
    subject: 'Writing',
    problems: 16,
    type: 'SAT Practice',
    unit: 'Writing Unit #1',
    difficulty: 'Difficult',
    timeEstimate: '62',
    source: 'Built-In',
    classifications: ['Right Triangles', 'Math', "Lots Of Math"],
  },
  {
    id: 4,
    title: 'Worksheet 4',
    subject: 'Writing',
    problems: 14,
    type: 'SAT Practice',
    unit: 'Mixed Unit #6',
    difficulty: 'Mixed',
    timeEstimate: '31',
    source: 'User Created',
    classifications: ['Trigonometry', 'More Math', "Lots Of Math"],
  },
  {
    id: 5,
    title: 'Worksheet 5',
    subject: 'Reading',
    problems: 21,
    type: 'Mixed',
    unit: 'Reading Unit #2',
    difficulty: 'Medium',
    timeEstimate: '23',
    source: 'Built-In',
    classifications: ['Trigonometry', 'Math', "Lots Of Math"],
  },
  {
    id: 6,
    title: 'Worksheet 6',
    subject: 'Math',
    problems: 30,
    type: 'Mixed',
    unit: 'Math Unit #4',
    difficulty: 'Difficult',
    timeEstimate: '58',
    source: 'User Created',
    classifications: ['Right Triangles', 'Trigonometry', 'More Math'],
  },
];
