export default [
  {
    id: 1,
    subject: 'Reading',
    timeEstimate: '14',
    unit: 'Reading Unit #2',
    title: 'Reading Something 1',
    type: 'Challenge + Practice',
    problems: '20',
    pageNumber: '128',
  },
  {
    id: 2,
    subject: 'Math',
    timeEstimate: '30',
    unit: 'Math Unit #4',
    title: 'Pythagorean Theorem',
    type: 'Challenge + Practice',
    problems: '16',
    pageNumber: '132',
  },
  {
    id: 3,
    subject: 'Reading',
    timeEstimate: '23',
    unit: 'Reading Unit #3',
    title: 'More Reading Stuff',
    type: 'Reading from Workbook',
    problems: '20',
    pageNumber: '141',
  },
  {
    id: 4,
    subject: 'Reading',
    timeEstimate: '31',
    unit: 'Reading Unit #6',
    title: 'Reading Someing 7',
    type: 'Challenge + Practice',
    problems: '17',
    pageNumber: '127',
  },
  {
    id: 5,
    subject: 'Reading',
    timeEstimate: '65',
    unit: 'Reading Unit #4',
    title: 'Reading Someing 4',
    type: 'Homework Drill',
    problems: '19',
    pageNumber: '120',
  },
  {
    id: 6,
    subject: 'Reading',
    timeEstimate: '50',
    unit: 'Reading Unit #9',
    title: 'Reading Someing 9',
    type: 'Challenge + Practice',
    problems: '22',
    pageNumber: '141',
  },
  {
    id: 7,
    subject: 'Reading',
    timeEstimate: '31',
    unit: 'Reading Unit #1',
    title: 'Reading Someing 1',
    type: 'Homework Drill',
    problems: '29',
    pageNumber: '136',
  },
  {
    id: 8,
    subject: 'Writing',
    timeEstimate: '48',
    unit: 'Writing Unit #5',
    title: 'Writing Lesson 5',
    type: 'Homework Drill',
    problems: '14',
    pageNumber: '117',
  },
  {
    id: 9,
    subject: 'Writing',
    timeEstimate: '48',
    unit: 'Writing Unit #5',
    title: 'Writing Lesson 5',
    type: 'Reading from Workbook',
    problems: '14',
    pageNumber: '117',
  },
];