export default [
  {
    id: 1,
    worksheetName: 'Some SAT Problems about Triangles',
    subject: 'Math',
    score: '',
    description: 'test description',
    problemType: 'Skill Builders',
    difficulty: 'Basic',
    timeEstimate: '14',
    assignDate: '1/27/19',
    assignTime: '3:01 PM',
    availableDate: '1/27/19',
    dueDate: '2/10/19',
    dueTime: '9:32 AM',
    completionDate: '3/12/19',
    completionTime: '2:53 PM',
    completedProblems: 3,
    completionLevel: 'Complete',
    unit: 'Reading Unit #4',
    passage: '214',
    type: 'challenge + practice',
    flags: [],
    status: 'Assigned',
    disabled: true,
    late: false,
    topic: 'trigonometry',
    worksheetSource: 'Built-In',
    classifications: ['Special Right Triangles', 'Volumes'],
    totalVideoMinutesWatched: '77',
    totalVideoMinutesAllMissedProblems: '214',
    passages: [
      {
        id: 1,
        subject: 'reading',
        title: 'Passage Title 1',
        problems: [
          {
            id: 1,
            subject: 'math',
            difficulty: 'easy',
            type: 'skillBuilder',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
          {
            id: 3,
            subject: 'reading',
            difficulty: 'hard',
            type: 'satPractice',
            inWorkbook: false,
            disabled: true,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
        ],
      },
      {
        id: 2,
        subject: 'writing',
        title: 'Passage Title 2',
        problems: [
          {
            id: 2,
            subject: 'reading',
            difficulty: 'easy',
            type: 'satPractice',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
          {
            id: 4,
            subject: 'writing',
            difficulty: 'medium',
            type: 'skillBuilder',
            inWorkbook: false,
            topics: [
              'trigonometry',
            ],
          },
        ],
      },
      {
        id: 3,
        subject: 'math',
        title: 'Passage Title 3',
        problems: [
          {
            id: 5,
            subject: 'writing',
            difficulty: 'hard',
            type: 'skillBuilder',
            inWorkbook: false,
            disabled: true,
            topics: [
              'rightTriangles',
            ],
          },
          {
            id: 6,
            subject: 'math',
            difficulty: 'medium',
            type: 'satPractice',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
        ],
      },
    ],
    problems: [
      {
        id: 1,
        subject: 'math',
        difficulty: 'easy',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 2,
        subject: 'reading',
        difficulty: 'easy',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 3,
        subject: 'reading',
        difficulty: 'hard',
        type: 'satPractice',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 4,
        subject: 'writing',
        difficulty: 'medium',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'trigonometry',
        ],
      },
      {
        id: 5,
        subject: 'writing',
        difficulty: 'hard',
        type: 'skillBuilder',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
        ],
      },
      {
        id: 6,
        subject: 'math',
        difficulty: 'medium',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
    ],
  },
  {
    id: 2,
    worksheetName: 'Worksheet 2',
    subject: 'Reading',
    score: '',
    description: '',
    problemType: 'Skill Builders',
    difficulty: 'Basic',
    timeEstimate: '30',
    assignDate: '1/19/19',
    assignTime: '3:01 PM',
    availableDate: '1/19/19',
    dueDate: '2/02/19',
    dueTime: '9:32 AM',
    completionDate: '',
    completionTime: '',
    completedProblems: 2,
    completionLevel: 'Not Started',
    unit: 'Reading Unit #4',
    passage: '51',
    type: 'challenge + practice',
    flags: [{ title: 'one', status: 'reviewed' }, { title: 'two', status: 'reviewed' }, { title: 'three', status: 'toReview' }],
    status: 'Assigned',
    disabled: false,
    late: true,
    topic: 'rightTriangles',
    worksheetSource: 'User Created',
    classifications: ['Math', 'More Math', "Lots Of Math"],
    totalVideoMinutesWatched: '77',
    totalVideoMinutesAllMissedProblems: '214',
    passages: [
      {
        id: 1,
        subject: 'reading',
        title: 'Passage Title 1',
        problems: [
          {
            id: 1,
            subject: 'math',
            difficulty: 'easy',
            type: 'skillBuilder',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
          {
            id: 3,
            subject: 'reading',
            difficulty: 'hard',
            type: 'satPractice',
            inWorkbook: false,
            disabled: true,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
        ],
      },
      {
        id: 2,
        subject: 'writing',
        title: 'Passage Title 2',
        problems: [
          {
            id: 2,
            subject: 'reading',
            difficulty: 'easy',
            type: 'satPractice',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
          {
            id: 4,
            subject: 'writing',
            difficulty: 'medium',
            type: 'skillBuilder',
            inWorkbook: false,
            topics: [
              'trigonometry',
            ],
          },
        ],
      },
    ],
    problems: [
      {
        id: 1,
        subject: 'math',
        difficulty: 'easy',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 2,
        subject: 'reading',
        difficulty: 'easy',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 3,
        subject: 'reading',
        difficulty: 'hard',
        type: 'satPractice',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 4,
        subject: 'writing',
        difficulty: 'medium',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'trigonometry',
        ],
      },
      {
        id: 5,
        subject: 'writing',
        difficulty: 'hard',
        type: 'skillBuilder',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
        ],
      },
      {
        id: 6,
        subject: 'math',
        difficulty: 'medium',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
    ],
  },
  {
    id: 3,
    worksheetName: 'Worksheet 3',
    subject: 'Math',
    score: '81',
    description: '',
    problemType: 'SAT Practice',
    difficulty: 'Advanced',
    timeEstimate: '24',
    assignDate: '1/11/19',
    assignTime: '3:01 PM',
    availableDate: '1/11/19',
    dueDate: '2/12/19',
    dueTime: '9:32 AM',
    completionDate: '3/12/19',
    completionTime: '2:53 PM',
    completedProblems: 4,
    completionLevel: 'Complete',
    unit: 'Reading Unit #4',
    passage: '121',
    type: 'challenge + practice',
    flags: [],
    status: 'Accomplished',
    disabled: false,
    late: false,
    topic: 'rightTriangles',
    worksheetSource: 'Built-In',
    classifications: ['Right Triangles', 'Math', "Lots Of Math"],
    totalVideoMinutesWatched: '124',
    totalVideoMinutesAllMissedProblems: '312',
    passages: [
      {
        id: 1,
        subject: 'reading',
        title: 'Passage Title 1',
        problems: [
          {
            id: 1,
            subject: 'math',
            difficulty: 'easy',
            type: 'skillBuilder',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
          {
            id: 3,
            subject: 'reading',
            difficulty: 'hard',
            type: 'satPractice',
            inWorkbook: false,
            disabled: true,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
        ],
      },
      {
        id: 3,
        subject: 'math',
        title: 'Passage Title 3',
        problems: [
          {
            id: 5,
            subject: 'writing',
            difficulty: 'hard',
            type: 'skillBuilder',
            inWorkbook: false,
            disabled: true,
            topics: [
              'rightTriangles',
            ],
          },
          {
            id: 6,
            subject: 'math',
            difficulty: 'medium',
            type: 'satPractice',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
        ],
      },
    ],
    problems: [
      {
        id: 1,
        subject: 'math',
        difficulty: 'easy',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 2,
        subject: 'reading',
        difficulty: 'easy',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 3,
        subject: 'reading',
        difficulty: 'hard',
        type: 'satPractice',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 4,
        subject: 'writing',
        difficulty: 'medium',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'trigonometry',
        ],
      },
      {
        id: 5,
        subject: 'writing',
        difficulty: 'hard',
        type: 'skillBuilder',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
        ],
      },
    ],
  },
  {
    id: 4,
    worksheetName: 'Worksheet 4',
    subject: 'Writing',
    score: '32',
    description: '',
    problemType: 'SAT Practice',
    difficulty: 'Mixed',
    timeEstimate: '31',
    assignDate: '1/24/19',
    assignTime: '3:01 PM',
    availableDate: '1/24/19',
    dueDate: '2/27/19',
    dueTime: '9:32 AM',
    completionDate: '',
    completionTime: '',
    completedProblems: 1,
    completionLevel: 'Started',
    unit: 'Reading Unit #4',
    passage: '128',
    type: 'challenge + practice',
    flags: [{ title: 'one', status: 'reviewed' }, { title: 'two', status: 'reviewed' }, { title: 'three', status: 'toReview' }, { title: 'four', status: 'toReview' }],
    status: 'Beginning',
    disabled: false,
    late: true,
    topic: 'trigonometry',
    worksheetSource: 'User Created',
    classifications: ['Trigonometry', 'More Math', "Lots Of Math"],
    totalVideoMinutesWatched: '311',
    totalVideoMinutesAllMissedProblems: '401',
    passages: [
      {
        id: 2,
        subject: 'writing',
        title: 'Passage Title 2',
        problems: [
          {
            id: 2,
            subject: 'reading',
            difficulty: 'easy',
            type: 'satPractice',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
          {
            id: 4,
            subject: 'writing',
            difficulty: 'medium',
            type: 'skillBuilder',
            inWorkbook: false,
            topics: [
              'trigonometry',
            ],
          },
        ],
      },
      {
        id: 3,
        subject: 'math',
        title: 'Passage Title 3',
        problems: [
          {
            id: 5,
            subject: 'writing',
            difficulty: 'hard',
            type: 'skillBuilder',
            inWorkbook: false,
            disabled: true,
            topics: [
              'rightTriangles',
            ],
          },
          {
            id: 6,
            subject: 'math',
            difficulty: 'medium',
            type: 'satPractice',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
        ],
      },
    ],
    problems: [
      {
        id: 1,
        subject: 'math',
        difficulty: 'easy',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 2,
        subject: 'reading',
        difficulty: 'easy',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 3,
        subject: 'reading',
        difficulty: 'hard',
        type: 'satPractice',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 4,
        subject: 'writing',
        difficulty: 'medium',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'trigonometry',
        ],
      },
      {
        id: 6,
        subject: 'math',
        difficulty: 'medium',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
    ],
  },
  {
    id: 5,
    worksheetName: 'Worksheet 5',
    subject: 'Reading',
    score: '93',
    description: '',
    problemType: 'Mixed',
    difficulty: 'Mixed',
    timeEstimate: '23',
    assignDate: '1/12/19',
    assignTime: '3:01 PM',
    availableDate: '1/12/19',
    dueDate: '2/03/19',
    dueTime: '9:32 AM',
    completionDate: '3/12/19',
    completionTime: '2:53 PM',
    completedProblems: 3,
    completionLevel: 'Instructor Editing',
    unit: 'Reading Unit #4',
    passage: '73',
    type: 'challenge + practice',
    flags: [{ title: 'one', status: 'toReview' }, { title: 'two', status: 'toReview' }],
    status: 'Developing',
    disabled: false,
    late: false,
    topic: 'trigonometry',
    worksheetSource: 'Built-In',
    classifications: ['Trigonometry', 'Math', "Lots Of Math"],
    totalVideoMinutesWatched: '51',
    totalVideoMinutesAllMissedProblems: '200',
    passages: [
      {
        id: 1,
        subject: 'reading',
        title: 'Passage Title 1',
        problems: [
          {
            id: 1,
            subject: 'math',
            difficulty: 'easy',
            type: 'skillBuilder',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
          {
            id: 3,
            subject: 'reading',
            difficulty: 'hard',
            type: 'satPractice',
            inWorkbook: false,
            disabled: true,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
        ],
      },
    ],
    problems: [
      {
        id: 1,
        subject: 'math',
        difficulty: 'easy',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 2,
        subject: 'reading',
        difficulty: 'easy',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 3,
        subject: 'reading',
        difficulty: 'hard',
        type: 'satPractice',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 5,
        subject: 'writing',
        difficulty: 'hard',
        type: 'skillBuilder',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
        ],
      },
      {
        id: 6,
        subject: 'math',
        difficulty: 'medium',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
    ],
  },
  {
    id: 6,
    worksheetName: 'Worksheet 6',
    subject: 'Writing',
    score: '64',
    description: '',
    problemType: 'Mixed',
    difficulty: 'Advanced',
    timeEstimate: '65',
    assignDate: '1/09/19',
    assignTime: '3:01 PM',
    availableDate: '1/09/19',
    dueDate: '2/12/19',
    dueTime: '9:32 AM',
    completionDate: '',
    completionTime: '',
    completedProblems: 4,
    completionLevel: 'Not Started',
    unit: 'Reading Unit #4',
    passage: '153',
    type: 'challenge + practice',
    flags: [],
    status: 'Developing',
    disabled: false,
    late: false,
    topic: 'rightTriangles',
    worksheetSource: 'User Created',
    classifications: ['Right Triangles', 'Trigonometry', 'More Math'],
    totalVideoMinutesWatched: '83',
    totalVideoMinutesAllMissedProblems: '305',
    passages: [
      {
        id: 3,
        subject: 'math',
        title: 'Passage Title 3',
        problems: [
          {
            id: 5,
            subject: 'writing',
            difficulty: 'hard',
            type: 'skillBuilder',
            inWorkbook: false,
            disabled: true,
            topics: [
              'rightTriangles',
            ],
          },
          {
            id: 6,
            subject: 'math',
            difficulty: 'medium',
            type: 'satPractice',
            inWorkbook: false,
            topics: [
              'rightTriangles',
              'trigonometry',
            ],
          },
        ],
      },
    ],
    problems: [
      {
        id: 1,
        subject: 'math',
        difficulty: 'easy',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 2,
        subject: 'reading',
        difficulty: 'easy',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
      {
        id: 4,
        subject: 'writing',
        difficulty: 'medium',
        type: 'skillBuilder',
        inWorkbook: false,
        topics: [
          'trigonometry',
        ],
      },
      {
        id: 5,
        subject: 'writing',
        difficulty: 'hard',
        type: 'skillBuilder',
        inWorkbook: false,
        disabled: true,
        topics: [
          'rightTriangles',
        ],
      },
      {
        id: 6,
        subject: 'math',
        difficulty: 'medium',
        type: 'satPractice',
        inWorkbook: false,
        topics: [
          'rightTriangles',
          'trigonometry',
        ],
      },
    ],
  },
];
