export default [
  {
    id: 1,
    accountInfo: {
      lastName: 'Bezos',
      firstName: 'Jeff',
      email: 'jeff-bezos@gmail.com',
      gender: 'Male',
    },
    contactInfo: {
      phone: '1234567890',
      streetAddress: '1234 Test Road',
      city: 'Austin',
      state: 'TX',
      zip: '78751',
    },
    basicInfo: {
      activeStudents: 15,
      pastStudents: 24,
      unactivatedStudents: 29,
      averageImprovement: 185,
      averageInitialScore: 1037,
      averageFinalScore: 1218,
      studentsAchievingTargetScore: 12,
    },
  },
  {
    id: 2,
    accountInfo: {
      lastName: 'Chavarro',
      firstName: 'Christian',
      email: 'christian-chavarro@gmail.com',
      gender: 'Male',
    },
    contactInfo: {
      phone: '1234567890',
      streetAddress: '1234 Test Road',
      city: 'Miami',
      state: 'TX',
      zip: '78751',
    },
    basicInfo: {
      activeStudents: 12,
      pastStudents: 73,
      unactivatedStudents: 12,
      averageImprovement: 200,
      averageInitialScore: 1000,
      averageFinalScore: 1213,
      studentsAchievingTargetScore: 14,
    },
  },
  {
    id: 3,
    accountInfo: {
      lastName: 'Chavis',
      firstName: 'Cellena',
      email: 'cellena-chavis@gmail.com',
      gender: 'Male',
    },
    contactInfo: {
      phone: '1234567890',
      streetAddress: '1234 Test Road',
      city: 'Miami',
      state: 'TX',
      zip: '78751',
    },
    basicInfo: {
      activeStudents: 44,
      pastStudents: 32,
      unactivatedStudents: 5,
      averageImprovement: 221,
      averageInitialScore: 1200,
      averageFinalScore: 1400,
      studentsAchievingTargetScore: 23,
    },
  },
  {
    id: 4,
    accountInfo: {
      lastName: 'Smith',
      firstName: 'Will',
      email: 'will-smithgmail.com',
      gender: 'Male',
    },
    contactInfo: {
      phone: '1234567890',
      streetAddress: '1234 Test Road',
      city: 'Austin',
      state: 'TX',
      zip: '78751',
    },
    basicInfo: {
      activeStudents: 22,
      pastStudents: 10,
      unactivatedStudents: 12,
      averageImprovement: 261,
      averageInitialScore: 1100,
      averageFinalScore: 1233,
      studentsAchievingTargetScore: 13,
    },
  },
  {
    id: 5,
    accountInfo: {
      lastName: 'Lumberjack',
      firstName: 'Arnold',
      email: 'arnold-lumberjack@gmail.com',
      gender: 'Male',
    },
    contactInfo: {
      phone: '1234567890',
      streetAddress: '1234 Test Road',
      city: 'Austin',
      state: 'TX',
      zip: '78751',
    },
    basicInfo: {
      activeStudents: 11,
      pastStudents: 24,
      unactivatedStudents: 62,
      averageImprovement: 123,
      averageInitialScore: 1269,
      averageFinalScore: 1459,
      studentsAchievingTargetScore: 9,
    },
  },
  {
    id: 6,
    accountInfo: {
      lastName: 'Duck',
      firstName: 'Donald',
      email: 'donald-duck@gmail.com',
      gender: 'Male',
    },
    contactInfo: {
      phone: '1234567890',
      streetAddress: '1234 Test Road',
      city: 'Austin',
      state: 'TX',
      zip: '78751',
    },
    basicInfo: {
      activeStudents: 45,
      pastStudents: 14,
      unactivatedStudents: 31,
      averageImprovement: 205,
      averageInitialScore: 1129,
      averageFinalScore: 1367,
      studentsAchievingTargetScore: 44,
    },
  },
];
