export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const SET_STUDENTS = 'SET_STUDENTS';
export const ADD_STUDENT = 'ADD_STUDENT';
export const SET_STUDENTS_CALENDAR_ASSIGN_LESSONS_MODAL_OPEN = 'SET_STUDENTS_CALENDAR_ASSIGN_LESSONS_MODAL_OPEN';
export const SET_STUDENTS_CALENDAR_ASSIGN_WORKSHEETS_MODAL_OPEN = 'SET_STUDENTS_CALENDAR_ASSIGN_WORKSHEETS_MODAL_OPEN';
export const SET_STUDENTS_CALENDAR_CALENDAR_ROWS = 'SET_STUDENTS_CALENDAR_CALENDAR_ROWS';