export const FETCH_STUDENTS = 'FETCH_STUDENTS';
export const SET_STUDENTS = 'SET_STUDENTS';
export const CREATE_STUDENT = 'CREATE_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const SET_STUDENTS_CALENDAR_ASSIGN_LESSONS_MODAL_OPEN = 'SET_STUDENTS_CALENDAR_ASSIGN_LESSONS_MODAL_OPEN';
export const SET_STUDENTS_CALENDAR_ASSIGN_WORKSHEETS_MODAL_OPEN = 'SET_STUDENTS_CALENDAR_ASSIGN_WORKSHEETS_MODAL_OPEN';
export const SET_STUDENTS_CALENDAR_CALENDAR_ROWS = 'SET_STUDENTS_CALENDAR_CALENDAR_ROWS';