export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const SEARCH_STUDENTS = "SEARCH_STUDENTS";
export const SET_STUDENTS = "SET_STUDENTS";
export const CREATE_STUDENT = "CREATE_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const UPDATE_STUDENT_ADDRESS = "UPDATE_STUDENT_ADDRESS";
export const UPDATE_STUDENT_CITY = "UPDATE_STUDENT_CITY";
export const UPDATE_STUDENT_EMAIL = "UPDATE_STUDENT_EMAIL";
export const UPDATE_STUDENT_FIRSTNAME = "UPDATE_STUDENT_FIRSTNAME";
export const UPDATE_STUDENT_LASTNAME = "UPDATE_STUDENT_LASTNAME";
export const UPDATE_STUDENT_PHONE = "UPDATE_STUDENT_PHONE";
export const UPDATE_STUDENT_STATE = "UPDATE_STUDENT_STATE";
export const UPDATE_STUDENT_ZIP = "UPDATE_STUDENT_ZIP";
export const SET_STUDENTS_CALENDAR_ASSIGN_LESSONS_MODAL_OPEN =
  "SET_STUDENTS_CALENDAR_ASSIGN_LESSONS_MODAL_OPEN";
export const SET_STUDENTS_CALENDAR_ASSIGN_WORKSHEETS_MODAL_OPEN =
  "SET_STUDENTS_CALENDAR_ASSIGN_WORKSHEETS_MODAL_OPEN";
export const SET_STUDENTS_CALENDAR_CALENDAR_ROWS = "SET_STUDENTS_CALENDAR_CALENDAR_ROWS";
export const SET_IS_VISIBLE_TOP_BAR = "SET_IS_VISIBLE_TOP_BAR";

export const SET_ACTIVE_TEST_SCORES = "SET_ACTIVE_TEST_SCORES";
export const GET_TESTS = "GET_TESTS";
export const SET_STUDENT_TESTS = "SET_STUDENT_TESTS";
export const SET_STUDENT_COMPLETED_TESTS = "SET_STUDENT_COMPLETED_TESTS";
export const SET_STUDENT_OVERDUE_TESTS = "SET_STUDENT_OVERDUE_TESTS";
export const SET_STUDENT_ASSIGNED_TESTS = "SET_STUDENT_ASSIGNED_TESTS";

export const FETCH_STUDENT_TEST_SECTIONS = "FETCH_STUDENT_TEST_SECTIONS";
export const SET_STUDENT_SECTIONS = "SET_STUDENT_SECTIONS";

export const FETCH_LESSON_LIST = 'FETCH_LESSON_LIST';
export const FETCH_LESSON_LIST_SUCCESS = 'FETCH_LESSON_LIST_SUCCESS';
export const FETCH_LESSON_LIST_FAIL = 'FETCH_LESSON_LIST_FAIL';

export const FETCH_STUDENT_LESSON_LIST = 'FETCH_STUDENT_LESSON_LIST';
export const FETCH_STUDENT_LESSSON_LIST_SUCCESS = 'FETCH_STUDENT_LESSON_LIST_SUCCUSS';
export const FETCH_STUDENT_LESSON_LIST_FAIL = 'FETCH_STUDENT_LESSON_LIST_FAIL';

export const MERGE_STUDENT_LESSON_LISTS = 'MERGE_STUDENT_LESSON_LISTS';

export const CHECKED_LESSON = 'CHECKED_LESSON';
export const CHECK_ALL_LESSONS = 'CHECK_ALL_LESSON';
export const UNCHECK_ALL_LESSONS = 'UNCHECK_ALL_LESSONS';

export const ADD_CHECKED_LESSON = 'ADD_CHECKED_LESSON';
export const REMOVE_CHECKED_LESSON = 'REMOVE_CHECKED_LESSON';

export const ASSIGN_STUDENT_LESSON = 'ASSIGN_STUDENT_LESSON';
export const ASSIGN_STUDENT_LESSON_SUCCESS = 'ASSIGN_STUDENT_LESSON_SUCCESS';
export const ASSIGN_STUDENT_LESSON_FAIL = 'ASSIGN_STUDENT_LESSON_FAIL';


export const FETCH_UNITS = 'FETCH_UNITS';
export const SET_UNIT_FILTER_OPTIONS = 'SET_UNIT_FILTER_OPTIONS';
export const SET_ACTIVE_STUDENT_TEST_ID = 'SET_ACTIVE_STUDENT_TEST_ID';

export const SET_ACTIVE_STUDENT_TOKEN = 'SET_ACTIVE_STUDENT_TOKEN';

export const RESET_STUDENT_LESSONS = 'RESET_STUDENT_LESSONS';
export const RESET_STUDENT_LESSONS_SUCCESS = 'RESET_STUDENT_LESSONS_SUCCESS';
export const RESET_STUDENT_LESSONS_FAIL = 'RESET_STUDENT_LESSONS_FAIL';
export const UNASSIGN_STUDENT_LESSON = 'UNASSIGN_STUDENT_LESSON';
export const UNASSIGN_STUDENT_LESSON_SUCCESS = 'UNASSIGN_STUDENT_LESSON_SUCCESS';
export const UNASSIGN_STUDENT_LESSON_FAIL = 'UNASSIGN_STUDENT_LESSON_FAIL';
export const RESCHEDULE_STUDENT_LESSONS = 'RESCHEDULE_STUDENT_LESSONS';
export const RESCHEDULE_STUDENT_LESSONS_SUCCESS = 'RESCHEDULE_STUDENT_LESSONS_SUCCESS';
export const RESCHEDULE_STUDENT_LESSONS_FAIL = 'RESCHEDULE_STUDENT_LESSONS_FAIL';
export const ADD_ALL_LESSONS = 'ADD_ALL_LESSONS';
export const REMOVE_ALL_LESSONS = 'REMOVE_ALL_LESSONS';

export const UPDATE_STUDENT_ACTIVATION = 'UPDATE_STUDENT_ACTIVATION';
export const UPDATE_STUDENT_ACTIVATION_SUCCESS = 'UPDATE_STUDENT_ACTIVATION_SUCCESS';
export const UPDATE_STUDENT_ACTIVATION_FAIL = 'UPDATE_STUDENT_ACTIVATION_FAIL';
