export default [
  {
    id: 1,
    // owner: {
    //   lastName: 'Bezos',
    //   firstName: 'Jeff',
    //   email: 'jeff-bezos@gmail.com',
    // },
    locationContactInfo: {
      locationName: 'Amazon',
      locationNickname: 'Amazon - Online Marketplace',
      // locationEmail: 'amazon@gmail.com',
      // locationPhoneNumber: '123-456-7889',
      // website: '',
      // locationStreetAddress: '',
      // locationCity: '',
      // locationState: '',
      // locationZip: '',
    },
    // locationEmailSettings: {
    //   automatedEmailOrigin: '',
    //   automatedEmailSalutation: '',
    // },
    // locationBranding: {
    //   locationUrl: '',
    //   headerColor1: '',
    //   headerColor2: '',
    //   headerLogoBackgroundColor: '',
    //   headerLogoBackgroundAlpha: '',
    //   horizontalLogoVariation: '',
    //   squareLogoVariation: '',
    //   backgroundImage: '',
    //   backgroundBlur: '',
    //   backgroundOverlayAlpha: '',
    //   studentWelcomeVideo: '',
    //   instructorWelcomeVideo: '',
    // },
    locationBasicInfo: {
      activeStudents: 15,
      pastStudents: 24,
      unactivatedStudents: 29,
      averageImprovement: 185,
      averageInitialScore: 1037,
      averageFinalScore: 1218,
      studentsAchievingTargetScore: 12,
    },
  },
  {
    id: 2,
    // owner: {
    //   lastName: 'Chavarro',
    //   firstName: 'Christian',
    //   email: 'christian-chavarro@gmail.com',
    // },
    locationContactInfo: {
      locationName: 'ChavarroLand',
      locationNickname: 'ChavarroLand - Austin, TX',
      // locationEmail: 'chavarro@gmail.com',
      // locationPhoneNumber: '535-432-2564',
      // website: '',
      // locationStreetAddress: '',
      // locationCity: '',
      // locationState: '',
      // locationZip: '',
    },
    // locationEmailSettings: {
    //   automatedEmailOrigin: '',
    //   automatedEmailSalutation: '',
    // },
    // locationBranding: {
    //   locationUrl: '',
    //   headerColor1: '',
    //   headerColor2: '',
    //   headerLogoBackgroundColor: '',
    //   headerLogoBackgroundAlpha: '',
    //   horizontalLogoVariation: '',
    //   squareLogoVariation: '',
    //   backgroundImage: '',
    //   backgroundBlur: '',
    //   backgroundOverlayAlpha: '',
    //   studentWelcomeVideo: '',
    //   instructorWelcomeVideo: '',
    // },
    locationBasicInfo: {
      activeStudents: 12,
      pastStudents: 73,
      unactivatedStudents: 12,
      averageImprovement: 200,
      averageInitialScore: 1000,
      averageFinalScore: 1213,
      studentsAchievingTargetScore: 14,
    },
  },
  {
    id: 3,
    // owner: {
    //   lastName: 'Chavis',
    //   firstName: 'Cellena',
    //   email: 'cellena-chavis@gmail.com',
    // },
    locationContactInfo: {
      locationName: 'Tutor Zone',
      locationNickname: 'Tutor Zone - Orlando, FL',
      // locationEmail: 'tutor-zone@gmail.com',
      // locationPhoneNumber: '331-145-7351',
      // website: '',
      // locationStreetAddress: '',
      // locationCity: '',
      // locationState: '',
      // locationZip: '',
    },
    // locationEmailSettings: {
    //   automatedEmailOrigin: '',
    //   automatedEmailSalutation: '',
    // },
    // locationBranding: {
    //   locationUrl: '',
    //   headerColor1: '',
    //   headerColor2: '',
    //   headerLogoBackgroundColor: '',
    //   headerLogoBackgroundAlpha: '',
    //   horizontalLogoVariation: '',
    //   squareLogoVariation: '',
    //   backgroundImage: '',
    //   backgroundBlur: '',
    //   backgroundOverlayAlpha: '',
    //   studentWelcomeVideo: '',
    //   instructorWelcomeVideo: '',
    // },
    locationBasicInfo: {
      activeStudents: 44,
      pastStudents: 32,
      unactivatedStudents: 5,
      averageImprovement: 221,
      averageInitialScore: 1200,
      averageFinalScore: 1400,
      studentsAchievingTargetScore: 23,
    },
  },
  {
    id: 4,
    // owner: {
    //   lastName: 'Smith',
    //   firstName: 'Will',
    //   email: 'will-smithgmail.com',
    // },
    locationContactInfo: {
      locationName: 'Fresh Prince',
      locationNickname: 'Fresh Prince - Philladelphia',
      // locationEmail: 'fresh-prince@gmail.com',
      // locationPhoneNumber: '331-145-7351',
      // website: '',
      // locationStreetAddress: '',
      // locationCity: '',
      // locationState: '',
      // locationZip: '',
    },
    // locationEmailSettings: {
    //   automatedEmailOrigin: '',
    //   automatedEmailSalutation: '',
    // },
    // locationBranding: {
    //   locationUrl: '',
    //   headerColor1: '',
    //   headerColor2: '',
    //   headerLogoBackgroundColor: '',
    //   headerLogoBackgroundAlpha: '',
    //   horizontalLogoVariation: '',
    //   squareLogoVariation: '',
    //   backgroundImage: '',
    //   backgroundBlur: '',
    //   backgroundOverlayAlpha: '',
    //   studentWelcomeVideo: '',
    //   instructorWelcomeVideo: '',
    // },
    locationBasicInfo: {
      activeStudents: 22,
      pastStudents: 10,
      unactivatedStudents: 12,
      averageImprovement: 261,
      averageInitialScore: 1100,
      averageFinalScore: 1233,
      studentsAchievingTargetScore: 13,
    },
  },
  {
    id: 5,
    // owner: {
    //   lastName: 'Lumberjack',
    //   firstName: 'Arnold',
    //   email: 'arnold-lumberjack@gmail.com',
    // },
    locationContactInfo: {
      locationName: 'Lumberjack Tutoring',
      locationNickname: 'Lumberjack Tutoring - Canada',
      // locationEmail: 'lumberjack-tutoring@gmail.com',
      // locationPhoneNumber: '331-145-7351',
      // website: '',
      // locationStreetAddress: '',
      // locationCity: '',
      // locationState: '',
      // locationZip: '',
    },
    // locationEmailSettings: {
    //   automatedEmailOrigin: '',
    //   automatedEmailSalutation: '',
    // },
    // locationBranding: {
    //   locationUrl: '',
    //   headerColor1: '',
    //   headerColor2: '',
    //   headerLogoBackgroundColor: '',
    //   headerLogoBackgroundAlpha: '',
    //   horizontalLogoVariation: '',
    //   squareLogoVariation: '',
    //   backgroundImage: '',
    //   backgroundBlur: '',
    //   backgroundOverlayAlpha: '',
    //   studentWelcomeVideo: '',
    //   instructorWelcomeVideo: '',
    // },
    locationBasicInfo: {
      activeStudents: 11,
      pastStudents: 24,
      unactivatedStudents: 62,
      averageImprovement: 123,
      averageInitialScore: 1269,
      averageFinalScore: 1459,
      studentsAchievingTargetScore: 9,
    },
  },
  {
    id: 6,
    // owner: {
    //   lastName: 'Duck',
    //   firstName: 'Donald',
    //   email: 'donald-duck@gmail.com',
    // },
    locationContactInfo: {
      locationName: 'Disney Learning',
      locationNickname: 'Disney Learning - San Francisco, CA',
      // locationEmail: 'disney-learning@gmail.com',
      // locationPhoneNumber: '331-145-7351',
      // website: '',
      // locationStreetAddress: '',
      // locationCity: '',
      // locationState: '',
      // locationZip: '',
    },
    // locationEmailSettings: {
    //   automatedEmailOrigin: '',
    //   automatedEmailSalutation: '',
    // },
    // locationBranding: {
    //   locationUrl: '',
    //   headerColor1: '',
    //   headerColor2: '',
    //   headerLogoBackgroundColor: '',
    //   headerLogoBackgroundAlpha: '',
    //   horizontalLogoVariation: '',
    //   squareLogoVariation: '',
    //   backgroundImage: '',
    //   backgroundBlur: '',
    //   backgroundOverlayAlpha: '',
    //   studentWelcomeVideo: '',
    //   instructorWelcomeVideo: '',
    // },
    locationBasicInfo: {
      activeStudents: 45,
      pastStudents: 14,
      unactivatedStudents: 31,
      averageImprovement: 205,
      averageInitialScore: 1129,
      averageFinalScore: 1367,
      studentsAchievingTargetScore: 44,
    },
  },
];
