const uuidv4 = require('uuid/v4');
export default [
  {
    id:uuidv4(),
    firstName: 'Bob',
    lastName: 'Smith',
    email: 'bob@smith.com',
    addressLine1: '4455 Main St',
    city: "Portland",
    state: "OR",
    zipCode: "98758",
    timeZone: "Pacific",
    avatarURL: "https://ichef.bbci.co.uk/news/320/media/images/82399000/jpg/_82399978_75952740.jpg",
  },
  {
    id:uuidv4(),
    firstName: 'Jeff',
    lastName: 'Bezos',
    email: 'jeff-bezos@email.com',
    addressLine1: '1234 Test Lane',
    city: 'Austin',
    state: 'TX',
    zipCode: '78757',
    timeZone: "Central",
    avatarURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUGJC2sKaR6OTgnDzoPwpHdpmEMY2rM8CLT8DbStzvnwQPf51Z",
  },
  {
    id:uuidv4(),
    firstName: 'Roger',
    lastName: 'Rabbit',
    email: 'roger-rabbit@email.com',
    addressLine1: '123 Baker Street',
    city: 'Paris',
    state: 'ID',
    zipCode: '88775',
    timeZone: "Mountain",
    avatarURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTM1yFuZbX_ObFSnyaESvq_1a_CTqCLTMURXViN5RyrQvHUm814",

  },
  {
    id:uuidv4(),
    firstName: 'Jack',
    lastName: 'InTheBox',
    email: 'jackinbox@email.com',
    addressLine1: '123 Baker Street',
    city: 'Paris',
    state: 'ID',
    zipCode: '88775',
    timeZone: "Mountain",
    avatarURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1vXjnr5RTywwY_6k8nOR7-Oz6B8ci4aNac-CGL9J3y3QRNLfo",
  },
  {
    id:uuidv4(),
    firstName: 'John',
    lastName: 'Jackson',
    email: 'john-jackson@email.com',
    addressLine1: "7643 Some Lane",
    city: "Topeka",
    state: "KS",
    zipCode: "56788",
    timeZone: "Central",
    avatarURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6Mh-9HGP3BCegpacxN9MtJFDCtextZ6c9cVC4xdnsuA0WsJgp5A",
  },
  {
    id:uuidv4(),
    firstName: 'Jennifer',
    lastName: 'Ownerson',
    email: 'jennifern@ownerson.com',
    addressLine1: "7643 Some Lane",
    city: "Kansas City",
    state: "KS",
    zipCode: "56788",
    timeZone: "Central",
    avatarURL: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS7O1-5ygT98zoHdS26QzqvClNlzTGqeP9fRIj-KTJKwI15QgSF",

  },
];
