 const sampleAnswers = [
  {
    id: 11,
    numeric: false,
    topic: 'writing',
    problem: 1,
    answer: "B",
    studentChoice: "C",
    correct: false,
    status: 'E',
    flagged: true,
    reviewed: false,
    tutorNotes: "work and study hard",
  },
  {
    id: 12,
    numeric: false,
    topic: 'writing',
    problem: 2,
    answer: "B",
    studentChoice: "B",
    correct: true,
    status: 'M',
    flagged: false,
    reviewed: false,
    studentNotes: "Lorem ipsum dolor sit amet sed diam nonummy nibh euismod tincidunt ut laoreet dolore?  tincidunt ut laoreet dolore?",
    tutorNotes: "work and study hard",
  },
  {
    id: 13,
    numeric: true,
    topic: 'writing',
    problem: 3,
    answer: 1492,
    studentChoice: 1492,
    correct: true,
    status: 'M',
    flagged: false,
    reviewed: false,
    tutorNotes: "work and study hard",
  },
  {
    id: 14,
    numeric: true,
    topic: 'writing',
    problem: 4,
    answer: 1.25,
    studentChoice: 5.71,
    correct: false,
    status: 'E  ',
    flagged: false,
    reviewed: false,
    tutorNotes: "work and study hard",
  },
];

export default sampleAnswers;