export default [
  {
    id: 1,
    subject: 'Math',
    version: 'SAT Practice #2',
    availableDate: '12/15/19',
    dueDate: '12/17/19',
    status: 'Exemplary',
    problems: 15,
    timeEstimate: '23',
    percentageComplete: '100',
    flags: [{}, {}, {}],
    disabled: false,
  },
  {
    id: 2,
    subject: 'Writing',
    version: 'SAT Practice #4',
    availableDate: '03/21/19',
    dueDate: '05/31/19',
    status: 'Developing',
    problems: 21,
    timeEstimate: '41',
    percentageComplete: '86',
    flags: [],
    disabled: false,
  },
  {
    id: 3,
    subject: 'Reading',
    version: 'SAT Practice #1',
    availableDate: '04/01/19',
    dueDate: '06/12/19',
    status: 'Assigned',
    problems: 42,
    timeEstimate: '57',
    percentageComplete: '0',
    flags: [],
    disabled: true,
  },
  {
    id: 4,
    subject: 'Writing',
    version: 'SAT Practice #6',
    availableDate: '07/11/19',
    dueDate: '07/13/19',
    status: 'Developing',
    problems: 17,
    timeEstimate: '21',
    percentageComplete: '72',
    flags: [{}],
    disabled: false,
  },
  {
    id: 5,
    subject: 'Math',
    version: 'SAT Practice #5',
    availableDate: '04/02/19',
    dueDate: '04/16/19',
    status: 'Exemplary',
    problems: 16,
    timeEstimate: '41',
    percentageComplete: '47',
    flags: [],
    disabled: false,
  },
];
